export const images = [
  {
    id: 1,
    url: "https://images.unsplash.com/photo-1714386148315-2f0e3eebcd5a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cmVkJTIwdmVsdmV0JTIwY2FrZXxlbnwwfHwwfHx8MA%3D%3D",
    alt: "Bakery products",
    title: "Bakery Products",
    description: "Up to 15% OFF",
  },
  {
    id: 2,
    url: "https://images.unsplash.com/photo-1714386148315-2f0e3eebcd5a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cmVkJTIwdmVsdmV0JTIwY2FrZXxlbnwwfHwwfHx8MA%3D%3D",
    alt: "Tea products",
    title: "Tea Products",
    description: "Up to 20% OFF",
  },
  {
    id: 3,
    url: "https://images.unsplash.com/photo-1714386148315-2f0e3eebcd5a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cmVkJTIwdmVsdmV0JTIwY2FrZXxlbnwwfHwwfHx8MA%3D%3D",
    alt: "Coffee products",
    title: "Coffee Products",
    description: "Up to 25% OFF",
  },
];

export const categoryImages = [
  {
    id: 1,
    url: "/categories/01.png",
    alt: "Bakery products",
    title: "Bakery Products",
    description: "Up to 15% OFF",
  },
  {
    id: 2,
    url: "/categories/02.png",
    alt: "Tea products",
    title: "Tea Products",
    description: "Up to 20% OFF",
  },
  {
    id: 3,
    url: "/categories/03.png",
    alt: "Coffee products",
    title: "Coffee Products",
    description: "Up to 25% OFF",
  },
  {
    id: 4,
    url: "/categories/04.png",
    alt: "Coffee products",
    title: "Coffee Products",
    description: "Up to 25% OFF",
  },
  {
    id: 5,
    url: "/categories/05.png",
    alt: "Coffee products",
    title: "Coffee Products",
    description: "Up to 25% OFF",
  },
];

export const categories = [
  {
    icon: "/icons/bakery.png",
    title: "Bakery",
    category: "Food",
    active: true,
  },
  {
    icon: "/icons/coffee.png",
    title: "Coffee",
    category: "Beverages",
    active: false,
  },
  {
    icon: "/icons/tea.png",
    title: "Tea",
    category: "Beverages",
    active: false,
  },
  {
    icon: "/icons/utensils.png",
    title: "Utensils",
    category: "Machineries",
    active: false,
  },
  {
    icon: "/icons/machineries.png",
    title: "Machineries",
    category: "Machineries",
    active: false,
  },
  { icon: "/icons/cake.png", title: "Cakes", category: "Food", active: false },
  {
    icon: "/icons/brownies.png",
    title: "Brownies",
    category: "Food",
    active: false,
  },
];

export const products = [
  {
    id: 1,
    img: "/products/Product1.png",
    name: "Product 1",
    brand: "Brand A",
    rating: 4.5,
    price: 1000,
    category: "Cakes",
  },
  {
    id: 2,
    img: "/products/1.png",
    name: "Product 2",
    brand: "Brand B",
    rating: 3.8,
    price: 1500,
    category: "Machineries",
  },
  {
    id: 3,
    img: "/products/2.png",
    name: "Product 3",
    brand: "Brand B",
    rating: 3.8,
    price: 1500,
    category: "Machineries",
  },
  {
    id: 4,
    img: "/products/3.png",
    name: "Product 4",
    brand: "Brand B",
    rating: 3.8,
    price: 1500,
    category: "Cakes",
  },
  {
    id: 5,
    img: "/products/4.png",
    name: "Product 5",
    brand: "Brand B",
    rating: 3.8,
    price: 1500,
    category: "Cakes",
  },
  {
    id: 6,
    img: "/products/brownie.png",
    name: "Chocolate Brownie With Mint Leaves Toppings",
    brand: "Brand B",
    rating: 4.8,
    price: 1500,
    category: "Brownies",
  },
  {
    id: 7,
    img: "/products/brownie.png",
    name: "Chocolate Brownie With Mint Leaves Toppings",
    brand: "Brand B",
    rating: 4.8,
    price: 1500,
    category: "Brownies",
  },
  {
    id: 8,
    img: "/products/cake1.png",
    name: "Chocolate Brownie With Mint Leaves Toppings",
    brand: "Brand B",
    rating: 4.8,
    price: 1500,
    category: "Cakes",
  },
  {
    id: 9,
    img: "/products/cake1.png",
    name: "Chocolate Brownie With Mint Leaves Toppings",
    brand: "Brand B",
    rating: 4.8,
    price: 1500,
    category: "Cakes",
  },
  {
    id: 10,
    img: "/products/cake1.png",
    name: "Chocolate Brownie With Mint Leaves Toppings",
    brand: "Brand B",
    rating: 4.8,
    price: 1500,
    category: "Cakes",
  },
  // Add more products as needed
];
